# Generated by Django 4.2.17 on 2025-01-07 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_rename_updated_on_about_last_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='last_updated',
            new_name='updated_on',
        ),
    ]
