# Generated by Django 4.2.17 on 2025-01-07 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_collaboraterequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollaborateRequest',
        ),
    ]
