# Generated by Django 4.2.17 on 2025-01-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_collaboraterequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboraterequest',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
